# Generated by Django 3.2.9 on 2022-01-09 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asegurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonSocial', models.CharField(max_length=20)),
                ('cuit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Autenticacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Autentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='AppURC.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Cobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('fechaContratacion', models.DateField()),
                ('fechaVigencia', models.DateTimeField()),
                ('detalle', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camara', models.CharField(max_length=40)),
                ('actividad', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Documentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formulario', models.IntegerField()),
                ('detalleCompradores', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exportando', models.BooleanField()),
                ('paisDestino', models.CharField(max_length=40)),
                ('clientes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Siniestros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaSiniestro', models.DateField()),
                ('reclamado', models.BooleanField()),
                ('montoImplicado', models.IntegerField()),
                ('detalle', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='poliza',
            fields=[
                ('poliza_id', models.AutoField(primary_key=True, serialize=False)),
                ('companiaAseg', models.CharField(max_length=40)),
                ('montoAsegurado', models.IntegerField()),
                ('cliente_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='AppURC.cliente')),
                ('coberturas', models.ManyToManyField(to='AppURC.Cobertura')),
            ],
        ),
        migrations.AddField(
            model_name='cobertura',
            name='numeroPoliza',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='AppURC.poliza'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='poliza_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppURC.poliza'),
        ),
    ]
