# Generated by Django 3.2.9 on 2021-12-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asegurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonSocial', models.CharField(max_length=20)),
                ('cuit', models.IntegerField()),
                ('mailContact', models.EmailField(max_length=254)),
                ('inicioCobertura', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exportando', models.BooleanField()),
                ('paisDestino', models.CharField(max_length=40)),
                ('clientes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=40)),
                ('montoAsegurado', models.IntegerField()),
            ],
        ),
    ]
