# Generated by Django 3.2.9 on 2021-12-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppURC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camara', models.CharField(max_length=40)),
                ('actividad', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Documentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formulario', models.IntegerField()),
                ('detalleCompradores', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='poliza',
            old_name='empresa',
            new_name='companiaAseg',
        ),
        migrations.RemoveField(
            model_name='asegurado',
            name='inicioCobertura',
        ),
        migrations.RemoveField(
            model_name='asegurado',
            name='mailContact',
        ),
    ]
