# Generated by Django 3.2.9 on 2022-01-09 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppURC', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='poliza_id',
        ),
        migrations.AddField(
            model_name='cliente',
            name='polizas_id',
            field=models.ManyToManyField(to='AppURC.poliza'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='identification',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='AppURC.usuario'),
        ),
    ]
