# Generated by Django 3.2.9 on 2022-01-12 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppURC', '0002_auto_20220109_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='polizas_id',
            field=models.ManyToManyField(blank=True, null=True, to='AppURC.poliza'),
        ),
        migrations.AlterField(
            model_name='cobertura',
            name='fechaVigencia',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='cliente_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='coberturas',
            field=models.ManyToManyField(blank=True, null=True, to='AppURC.Cobertura'),
        ),
    ]
