# Generated by Django 3.2.9 on 2022-01-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppURC', '0004_autenticacion_cliente_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Autenticacion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
