# Generated by Django 3.2.9 on 2022-01-03 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppURC', '0004_autenticacion_cliente_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autenticacion',
        ),
    ]
