# Generated by Django 3.2.9 on 2022-01-06 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppURC', '0005_auto_20220105_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='name',
            new_name='username',
        ),
    ]
