# Generated by Django 3.2.9 on 2022-01-03 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppURC', '0005_delete_autenticacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
